### ISSUE TITLE
quickplay problem

### ISSUE THREAD

**Issue by Ksawery0313** [AfterglowMC/AfterglowMC-Legacy#1]
sometimes if i press quickplay then it will go blackscreen

**Comment by liminalityyy** [comment]
This seems to be a weird issue with MultiMC straight up crashing upon the quickplay button being pressed, im not sure why this happens, as it works perfectly fine otherwise.

**Comment by liminalityyy** [comment]
Reminder: this is entirely random, if this happens, delete the world you tried loading via quickplay, in this case the default would be World 1
