### ISSUE TITLE
Sound [Fixed]

### ISSUE THREAD

**Issue by Vincent392** [AfterglowMC/AfterglowMC-Legacy#2]
Sound is gone.
Something to do with RetroPCM?

**Comment by liminalityyy** [comment]
yeah im not sure what causes this
im going to get onto this ASAP, thanks for telling me

**Comment by liminalityyy** [comment]
Happy to announce that with the help of Buj, we have resolved this issue
expect it to be fixed upon the release of the next build :D

**Comment by Vincent392** [comment]
Very Good. You can lock this now
