### ISSUE TITLE
crashed mid game

### ISSUE THREAD

**Issue by unnaturalistic** [AfterglowMC/AfterglowMC-Legacy#4]
java.lang.ArrayIndexOutOfBoundsException: -1
	at ci.a(ci.java:33)
	at ci.f(ci.java:115)
	at cz.a(cz.java:155)
	at cz.a(cz.java:108)
	at cz.b(cz.java:84)
	at cz.a(cz.java:50)
	at cz.a(cz.java:27)
	at cz.a(cz.java:14)
	at cn.a(cn.java:1790)
	at ek.b_(ek.java:18)
	at ge.j(ge.java:541)
	at dq.j(dq.java:17)
	at ge.e_(ge.java:194)
	at dq.e_(dq.java:21)
	at cn.e(cn.java:1162)
	at cn.c(cn.java:1129)
	at net.minecraft.client.Minecraft.i(Minecraft.java:979)
	at net.minecraft.client.Minecraft.run(Minecraft.java:468)
	at java.lang.Thread.run(Unknown Source)

**Comment by liminalityyy** [comment]
please do keep in mind that a full rewrite is around the corner.
also i cannot work with obfusacted classes can you please actually post the entire crash log

**Comment by Vladg24YT** [comment]
> cannot work with obfusacted classes

One could use the mappings file (usually `.tiny`) to find the class corresponding to the obfuscated names

**Comment by liminalityyy** [comment]
> One could use the mappings file (usually `.tiny`) to find the class corresponding to the obfuscated names

oh yeah

**Comment by Vincent392** [comment]
It's that simple!
(Thankfully I have never had to do that with PL or UNR.PRE2 AB)

**Comment by unnaturalistic** [comment]
> please do keep in mind that a full rewrite is around the corner. also i cannot work with obfusacted classes can you please actually post the entire crash log

I will actually
But the bug is pretty rare...

**Comment by orangeman12** [comment]
But the bug is pretty rare

**Comment by Vincent392** [comment]
Uhmmmmmm A Rare bug....
THAT MAKES IT EVEN HARDER!

**Comment by liminalityyy** [comment]
> But the bug is pretty rare...

it could just be alpha crashing. This happens a lot randomly
also if your loading world3, high chance thats why

**Comment by Vincent392** [comment]
> > But the bug is pretty rare...
> 
> it could just be alpha crashing. This happens a lot randomly also if your loading world3, high chance thats why

true. (World 3 hasn't crashed for me tho)

**Comment by unnaturalistic** [comment]
> > But the bug is pretty rare...
> 
> it could just be alpha crashing. This happens a lot randomly also if your loading world3, high chance thats why

so what i was doing was just jumping around using DASH
like b-hopping or something and it crashed

**Comment by unnaturalistic** [comment]
its pretty rare tho, might be a minecraft issue ¯\_(ツ)_/¯
